[package]
name                 = "quinn_runtime_bevy"
description          = "Quinn runtime implementation built on Bevy's IO task pool."
version              = "0.3.0"
authors.workspace    = true
edition.workspace    = true
license.workspace    = true
repository.workspace = true

[dependencies]
async-executor = "1.4"
async-io       = "1.9"
bevy_tasks     = "0.11"
futures-lite   = "1.0"
pin-project    = "1.0"
# crates.io quinn release (0.10.2) not compiling, use 0.10.2 git branch instead (https://github.com/quinn-rs/quinn/issues/1735)
quinn          = { git = "https://github.com/quinn-rs/quinn.git", rev = "0.10.2", default-features = false, features = ["native-certs", "tls-rustls"] }
quinn-udp      = { git = "https://github.com/quinn-rs/quinn.git", rev = "0.10.2", default-features = false }
